//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebianPackagesExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DebianPackagesExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DebianLogo {
            get {
                object obj = ResourceManager.GetObject("DebianLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation collection instance already created..
        /// </summary>
        internal static string Exception_LocalisationAlreadyCreated {
            get {
                return ResourceManager.GetString("Exception_LocalisationAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LICENSE.
        /// </summary>
        internal static string FileName_License {
            get {
                return ResourceManager.GetString("FileName_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msinfo32.exe.
        /// </summary>
        internal static string FileName_MSInfo {
            get {
                return ResourceManager.GetString("FileName_MSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/{0};component/Localisation/Localisation.xaml.
        /// </summary>
        internal static string PackString_Localisation {
            get {
                return ResourceManager.GetString("PackString_Localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*(?&lt;name&gt;[a-zA-Z0-9-]*):(?&lt;value&gt;.*).
        /// </summary>
        internal static string RegExPattern_PackageInfo {
            get {
                return ResourceManager.GetString("RegExPattern_PackageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutWindow_GroupBox_LoadedAssemblies_Header.
        /// </summary>
        internal static string ResKey_AboutWindow_GroupBox_LoadedAssemblies_Header {
            get {
                return ResourceManager.GetString("ResKey_AboutWindow_GroupBox_LoadedAssemblies_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutWindow_Title.
        /// </summary>
        internal static string ResKey_AboutWindow_Title {
            get {
                return ResourceManager.GetString("ResKey_AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_AllRightsReserved.
        /// </summary>
        internal static string ResKey_String_AllRightsReserved {
            get {
                return ResourceManager.GetString("ResKey_String_AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_DotNetVersionInfo.
        /// </summary>
        internal static string ResKey_String_DotNetVersionInfo {
            get {
                return ResourceManager.GetString("ResKey_String_DotNetVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_VersionInfo.
        /// </summary>
        internal static string ResKey_String_VersionInfo {
            get {
                return ResourceManager.GetString("ResKey_String_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisations.
        /// </summary>
        internal static string String_Localisations {
            get {
                return ResourceManager.GetString("String_Localisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCALISATION.XAML.
        /// </summary>
        internal static string String_MainLocalisationFile {
            get {
                return ResourceManager.GetString("String_MainLocalisationFile", resourceCulture);
            }
        }
    }
}
