//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebianPackagesExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DebianPackagesExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Application_x_deb {
            get {
                object obj = ResourceManager.GetObject("Application_x_deb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DebianLogo {
            get {
                object obj = ResourceManager.GetObject("DebianLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownloadPackage {
            get {
                object obj = ResourceManager.GetObject("DownloadPackage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation collection instance already created..
        /// </summary>
        internal static string Exception_LocalisationAlreadyCreated {
            get {
                return ResourceManager.GetString("Exception_LocalisationAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LICENSE.
        /// </summary>
        internal static string FileName_License {
            get {
                return ResourceManager.GetString("FileName_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msinfo32.exe.
        /// </summary>
        internal static string FileName_MSInfo {
            get {
                return ResourceManager.GetString("FileName_MSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoNext {
            get {
                object obj = ResourceManager.GetObject("GoNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoPrevious {
            get {
                object obj = ResourceManager.GetObject("GoPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenLink {
            get {
                object obj = ResourceManager.GetObject("OpenLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/{0};component/Localisation/Localisation.xaml.
        /// </summary>
        internal static string PackString_Localisation {
            get {
                return ResourceManager.GetString("PackString_Localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to architecture.
        /// </summary>
        internal static string RegEx_GroupName_Architecture {
            get {
                return ResourceManager.GetString("RegEx_GroupName_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to architectures.
        /// </summary>
        internal static string RegEx_GroupName_Architectures {
            get {
                return ResourceManager.GetString("RegEx_GroupName_Architectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baseurl.
        /// </summary>
        internal static string RegEx_GroupName_BaseUrl {
            get {
                return ResourceManager.GetString("RegEx_GroupName_BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codename.
        /// </summary>
        internal static string RegEx_GroupName_CodeName {
            get {
                return ResourceManager.GetString("RegEx_GroupName_CodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to component.
        /// </summary>
        internal static string RegEx_GroupName_Component {
            get {
                return ResourceManager.GetString("RegEx_GroupName_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to components.
        /// </summary>
        internal static string RegEx_GroupName_Components {
            get {
                return ResourceManager.GetString("RegEx_GroupName_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filename.
        /// </summary>
        internal static string RegEx_GroupName_FileName {
            get {
                return ResourceManager.GetString("RegEx_GroupName_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*(?&lt;name&gt;[a-zA-Z0-9-]*):(?&lt;value&gt;.*).
        /// </summary>
        internal static string RegEx_Pattern_PackageInfo {
            get {
                return ResourceManager.GetString("RegEx_Pattern_PackageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;name&gt;\w+)(: +)(?&lt;value&gt;.*)\s.
        /// </summary>
        internal static string RegEx_Pattern_ReleaseFile {
            get {
                return ResourceManager.GetString("RegEx_Pattern_ReleaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?&lt;baseurl&gt;http.+)/dists/(?&lt;codename&gt;.+)/(?&lt;component&gt;.+)/binary-(?&lt;architecture&gt;.+)/(?&lt;filename&gt;.+)$.
        /// </summary>
        internal static string RegEx_Pattern_SourcePackageInfoByLink {
            get {
                return ResourceManager.GetString("RegEx_Pattern_SourcePackageInfoByLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutWindow_GroupBox_LoadedAssemblies_Header.
        /// </summary>
        internal static string ResKey_AboutWindow_GroupBox_LoadedAssemblies_Header {
            get {
                return ResourceManager.GetString("ResKey_AboutWindow_GroupBox_LoadedAssemblies_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutWindow_Title.
        /// </summary>
        internal static string ResKey_AboutWindow_Title {
            get {
                return ResourceManager.GetString("ResKey_AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_AllRightsReserved.
        /// </summary>
        internal static string ResKey_String_AllRightsReserved {
            get {
                return ResourceManager.GetString("ResKey_String_AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_DotNetVersionInfo.
        /// </summary>
        internal static string ResKey_String_DotNetVersionInfo {
            get {
                return ResourceManager.GetString("ResKey_String_DotNetVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_DownloadCompleted.
        /// </summary>
        internal static string ResKey_String_DownloadCompleted {
            get {
                return ResourceManager.GetString("ResKey_String_DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_DownloadingFile_Formatted.
        /// </summary>
        internal static string ResKey_String_DownloadingFile_Formatted {
            get {
                return ResourceManager.GetString("ResKey_String_DownloadingFile_Formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_DownloadPackage.
        /// </summary>
        internal static string ResKey_String_DownloadPackage {
            get {
                return ResourceManager.GetString("ResKey_String_DownloadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_EmptyPackagesFile.
        /// </summary>
        internal static string ResKey_String_EmptyPackagesFile {
            get {
                return ResourceManager.GetString("ResKey_String_EmptyPackagesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_FileNotFound.
        /// </summary>
        internal static string ResKey_String_FileNotFound {
            get {
                return ResourceManager.GetString("ResKey_String_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_InvalidLink.
        /// </summary>
        internal static string ResKey_String_InvalidLink {
            get {
                return ResourceManager.GetString("ResKey_String_InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_NothingFound.
        /// </summary>
        internal static string ResKey_String_NothingFound {
            get {
                return ResourceManager.GetString("ResKey_String_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_OpenFileDialogFilter.
        /// </summary>
        internal static string ResKey_String_OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("ResKey_String_OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_OverwriteFile.
        /// </summary>
        internal static string ResKey_String_OverwriteFile {
            get {
                return ResourceManager.GetString("ResKey_String_OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_ParsingFile.
        /// </summary>
        internal static string ResKey_String_ParsingFile {
            get {
                return ResourceManager.GetString("ResKey_String_ParsingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_Ready.
        /// </summary>
        internal static string ResKey_String_Ready {
            get {
                return ResourceManager.GetString("ResKey_String_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String_VersionInfo.
        /// </summary>
        internal static string ResKey_String_VersionInfo {
            get {
                return ResourceManager.GetString("ResKey_String_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisations.
        /// </summary>
        internal static string String_Localisations {
            get {
                return ResourceManager.GetString("String_Localisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCALISATION.XAML.
        /// </summary>
        internal static string String_MainLocalisationFile {
            get {
                return ResourceManager.GetString("String_MainLocalisationFile", resourceCulture);
            }
        }
    }
}
